# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\rkala\OneDrive\Desktop\Thunder\Onboard Screenning\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def go_to_screen3():
    window.destroy()
    import onboarding_screen3


def exit_program():
    window.destroy()


window = Tk()

window.geometry("900x600")
window.configure(bg = "#105090")


canvas = Canvas(window, bg="#105090", height=600, width=900, bd=0, highlightthickness=0, relief="ridge")
canvas.place(x=0, y=0)
canvas.create_rectangle(212.0, 478.0, 700.0, 565.0, fill="#105090", outline="")

button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = Button(image=button_image_1, borderwidth=0, highlightthickness=0, command=go_to_screen3, relief="flat")
button_1.place(x=555.0, y=499.0, width=124.0, height=42.0)

button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"))
button_2 = Button(image=button_image_2, borderwidth=0, highlightthickness=0, command=exit_program, relief="flat")
button_2.place(x=244.0, y=502.0, width=124.0, height=42.0)

canvas.create_text(354.0, 73.0, anchor="nw", text="Flexibility", fill="#FFFDFD", font=("JacquesFrancois Regular", 40 * -1))
canvas.create_text(42.0, 186.0, anchor="nw", text="Structure, refine, and visualize your business plan with ease.", fill="#FFFFFF", font=("JacquesFrancois Regular", 30 * -1))

image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
canvas.create_image(347.0, 359.0, image=image_image_1)

image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
canvas.create_image(583.0, 353.0, image=image_image_2)

window.resizable(False, False)
window.mainloop()